# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        MainWindow.setSizeIncrement(QtCore.QSize(600, 400))
        MainWindow.setBaseSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.341, y1:0.034, x2:1, y2:0, stop:0 rgba(153, 0, 0, 245), stop:1 rgba(122, 17, 17, 246));\n"
"border-radius: 30px;\n"
"color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(160, 80, 271, 101))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setStyleSheet("background:none")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(141, 154, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background:none;\n"
"color: rgb(255, 255, 127);")
        self.label_2.setObjectName("label_2")
        self.loading = QtWidgets.QProgressBar(self.frame)
        self.loading.setGeometry(QtCore.QRect(50, 250, 501, 31))
        self.loading.setStyleSheet("*{\n"
"    background-color: rgb(255, 255, 127);    \n"
"    border-style:none;\n"
"    border-radius:10px;\n"
"    text-align: center;\n"
"    color: rgb(113, 113, 113)color\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.994, y2:0, stop:0 rgba(255, 232, 102, 255), stop:0.55 rgba(226, 235, 61, 255), stop:0.98 rgba(118, 200, 193, 255), stop:1 rgba(0, 0, 0, 0));\n"
"    border-radius:10px\n"
"}")
        self.loading.setProperty("value", 24)
        self.loading.setObjectName("loading")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(250, 280, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Modern No. 20")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background:none;\n"
"color: #fff")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<strong>O-</strong>Library"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>&quot;<span style=\" font-weight:600;\">pinjam - pinjam </span>buku jadi mudah&quot;</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>please wait...</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
